// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ydabaxstraujbxngzkna.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlkYWJheHN0cmF1amJ4bmd6a25hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzMTAwMDIsImV4cCI6MjA2Mzg4NjAwMn0.nV-_AnPBFMA2s7sk3B_CAi_Yt8vGQU1oyzKCimPOq7g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);